### ISSUE TITLE
You mentioned that this project took you a long long time of 34 minutes but developing the (sussy) IMPOSTER-DETECTION-ALGORITHM (TM) took you 9 years which wouldn't really leave a whole lot of time for the rest of the algorithm to be developed. This makes things very unclear and impostorous to me.

### ISSUE THREAD

**Issue by Giftzwerg02** [0xhiro/amongrust#1]
Please label this Issue with everything you have got and more, since I think that this is very important.

[Also, don't forget. (It is not a Rick-Roll... really, trust me, no cap)](https://www.youtube.com/watch?v=gWo12TtN9Kk)

[Yours sincerely, (this link might be a Rick-Roll)](https://www.youtube.com/watch?v=d3h7d6LidWk)

[amogus.](https://www.youtube.com/watch?v=lpiB2wMc49g)

**Comment by Giftzwerg02** [comment]
Why didn't you fix the issue yet?!?!?!?!!!??!?! ?! ?! ?!! ?! ?R"§Q%43250ß43 25432q ßtr43
wf43wk43wfj43wiozghj43üw tz9u43üwtu

**Comment by 0xhiro** [comment]
Technically speaking, the 9 years were spent on research and meditation, and then it was implemented in 34 minutes.
