### ISSUE TITLE
Imposter removal isn't clean 

### ISSUE THREAD

**Issue by jr-josh** [0xhiro/amongrust#2]
# Before imposters 

![image](https://user-images.githubusercontent.com/94854557/204112672-5ca8c2bb-aee7-4db1-a006-33e5365fbb78.png)

# Imposters

![image](https://user-images.githubusercontent.com/94854557/204112711-8a2baa3e-f3ce-4c62-b3c5-7cc00980cd5d.png)

# After imposter removal

![image](https://user-images.githubusercontent.com/94854557/204112737-e13e7077-862f-435c-9fc8-c24cc9fbe0e3.png)

**Comment by 0xhiro** [comment]
If i am correct, a curly brace is missing right?

**Comment by 0xhiro** [comment]
If so, besides the curly brace, is there any other error?

**Comment by jr-josh** [comment]
I think this is caused by line 116, ` if old_data.len() > index + 4 && index > 4 {` - if this check fails, deleting is never set to false.

**Comment by 0xhiro** [comment]
Thanks for the report crewmate! fixing this ASAP

**Comment by jr-josh** [comment]
My brain must have been scrambled by the imposter's reversinator to suggest that as the cause of the problem! The very same reversinator has scrambled the indexes when looking for the end of the amongus comment! MR incoming.

**Comment by jr-josh** [comment]
It was both! Two imposters!

**Comment by jr-josh** [comment]
Fixed  in  #7

**Comment by jr-josh** [comment]
Fixed on the staging branch now #7 is merged.
