### ISSUE TITLE
Add imposter kills

### ISSUE THREAD

**Issue by DocJade** [0xhiro/amongrust#6]
̿̿example
```
foo = sussy_function(69); // ඞ🔫ඞ
bar = String::From("sus")// ඞ🗡️ඞ
```

**Comment by 0xhiro** [comment]
Hmmm. Can you explain a little further what you mean?

**Comment by DocJade** [comment]
Sure! Instead of a big ASCII art, pick a random line, and append an amongi getting killed like in the game (examples: https://youtu.be/Lc-SvuC8SJU)

So
`println!("hello!");`
Would become
`println!("hello!");.   //ඞ🔫ඞ`

**Comment by 0xhiro** [comment]
Oh yeah! makes sense. Does not fit into the current scope of what amongrust does, but looks like a good feature to add if there will be any major design changes in the future.

**Comment by 0xhiro** [comment]
closing as not planned
